FROM node:20-alpine

RUN apk add --no-cache ffmpeg

RUN npm install -g n8n

ENV N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
ENV NODE_FUNCTION_ALLOW_EXTERNAL=*
ENV N8N_RUNNERS_ENABLED=true

EXPOSE 5678

CMD ["n8n"]
